export const generatePDF = async (documentText, title) => {
  const { default: jsPDF } = await import('jspdf');
  
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Header background
  doc.setFillColor(15, 14, 10);
  doc.rect(0, 0, pageWidth, 28, 'F');

  // App name in header
  doc.setTextColor(212, 180, 131);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('LexDraft', margin, 14);

  doc.setTextColor(180, 180, 160);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Professional Legal Document Generator', margin, 20);

  // Date in header right
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setTextColor(140, 130, 110);
  doc.setFontSize(8);
  doc.text(`Generated: ${today}`, pageWidth - margin, 20, { align: 'right' });

  // Document title
  doc.setTextColor(15, 14, 10);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  
  let yPos = 44;
  
  // Title box
  doc.setFillColor(250, 248, 240);
  doc.setDrawColor(196, 165, 90);
  doc.setLineWidth(0.5);
  doc.rect(margin, yPos - 8, contentWidth, 16, 'FD');
  
  doc.setTextColor(15, 14, 10);
  doc.text(title.toUpperCase(), pageWidth / 2, yPos + 1, { align: 'center' });

  yPos += 20;

  // Divider
  doc.setDrawColor(196, 165, 90);
  doc.setLineWidth(0.3);
  doc.line(margin, yPos, pageWidth - margin, yPos);

  yPos += 8;

  // Content
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(30, 28, 20);

  const lines = doc.splitTextToSize(documentText, contentWidth);
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    // Check if we need a new page
    if (yPos > pageHeight - 28) {
      // Footer on current page
      addFooter(doc, pageWidth, pageHeight, margin, doc.internal.getNumberOfPages());
      doc.addPage();
      
      // Header on new page
      doc.setFillColor(15, 14, 10);
      doc.rect(0, 0, pageWidth, 20, 'F');
      doc.setTextColor(212, 180, 131);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('LexDraft – ' + title, margin, 13);
      
      yPos = 30;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(30, 28, 20);
    }

    // Bold section headers (lines that are all caps or end with colon pattern)
    const trimmedLine = line.trim();
    if (
      (trimmedLine === trimmedLine.toUpperCase() && trimmedLine.length > 3 && !trimmedLine.match(/^\d/)) ||
      /^\d+\.\s+[A-Z\s]+$/.test(trimmedLine)
    ) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 14, 10);
    } else if (trimmedLine.match(/^[A-Z\s]{3,}:$/) || trimmedLine.match(/^(EMPLOYER|EMPLOYEE|LANDLORD|TENANT|ASSIGNOR|ASSIGNEE|PARTNER|PRINCIPAL|AGENT|FREELANCER|CLIENT|DISCLOSING|RECEIVING):/)) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 80, 30);
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 28, 20);
    }

    doc.text(line, margin, yPos);
    yPos += 5.2;
  }

  // Footer on last page
  addFooter(doc, pageWidth, pageHeight, margin, doc.internal.getNumberOfPages());

  // Save
  const filename = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.pdf`;
  doc.save(filename);
  return filename;
};

const addFooter = (doc, pageWidth, pageHeight, margin, pageNum) => {
  doc.setFillColor(245, 242, 232);
  doc.rect(0, pageHeight - 16, pageWidth, 16, 'F');
  
  doc.setDrawColor(196, 165, 90);
  doc.setLineWidth(0.3);
  doc.line(margin, pageHeight - 16, pageWidth - margin, pageHeight - 16);
  
  doc.setTextColor(100, 90, 70);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.text('This document was generated by LexDraft. Please consult a qualified attorney before use.', margin, pageHeight - 8);
  doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 8, { align: 'right' });
};

export const downloadAsText = (documentText, title) => {
  const blob = new Blob([documentText], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

export const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    document.body.appendChild(textArea);
    textArea.select();
    document.execCommand('copy');
    document.body.removeChild(textArea);
    return true;
  }
};
