import { Link } from 'react-router-dom';
import { Scale, Github, Mail } from 'lucide-react';

const appName = import.meta.env.VITE_APP_NAME || 'LexDraft';
const contactEmail = import.meta.env.VITE_CONTACT_EMAIL || 'support@lexdraft.com';

export default function Footer() {
  return (
    <footer className="bg-ink-900 text-ivory-100/70 mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          {/* Brand */}
          <div>
            <div className="flex items-center gap-2.5 mb-4">
              <div className="w-7 h-7 bg-gold-500/20 border border-gold-500/30 flex items-center justify-center rounded-sm">
                <Scale size={14} className="text-gold-400" />
              </div>
              <span className="font-display font-bold text-ivory-50 text-lg">{appName}</span>
            </div>
            <p className="font-body text-sm leading-relaxed text-ivory-100/50 max-w-xs">
              Professional legal document generation for individuals and businesses. Fast, accurate, and reliable.
            </p>
            <p className="mt-4 text-xs text-ivory-100/30 font-mono">
              v{import.meta.env.VITE_APP_VERSION || '1.0.0'}
            </p>
          </div>

          {/* Links */}
          <div>
            <h4 className="font-body text-xs uppercase tracking-widest text-gold-400/80 mb-4">Navigation</h4>
            <ul className="space-y-2.5">
              {[
                { to: '/', label: 'Home' },
                { to: '/templates', label: 'Browse Templates' },
                { to: '/saved', label: 'My Documents' },
              ].map(({ to, label }) => (
                <li key={to}>
                  <Link
                    to={to}
                    className="font-body text-sm text-ivory-100/50 hover:text-gold-400 transition-colors duration-200"
                  >
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Contact & Disclaimer */}
          <div>
            <h4 className="font-body text-xs uppercase tracking-widest text-gold-400/80 mb-4">Legal & Contact</h4>
            <p className="font-body text-xs text-ivory-100/40 leading-relaxed mb-4">
              Documents generated by {appName} are templates for informational purposes only. 
              Please consult a qualified attorney for legal advice.
            </p>
            <a
              href={`mailto:${contactEmail}`}
              className="inline-flex items-center gap-2 text-sm text-ivory-100/50 hover:text-gold-400 transition-colors"
            >
              <Mail size={14} />
              {contactEmail}
            </a>
          </div>
        </div>

        <div className="mt-12 pt-6 border-t border-ivory-100/10 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="font-body text-xs text-ivory-100/30">
            © {new Date().getFullYear()} {appName}. All rights reserved.
          </p>
          <p className="font-body text-xs text-ivory-100/30">
            Built with React + Vite + Tailwind CSS + Framer Motion
          </p>
        </div>
      </div>
    </footer>
  );
}
